name: BSN Frontend Pipeline

on:
  push: # 当有人向仓库分支推送代码时，会触发推送事件并运行此工作流。可使用 * 和 ** 通配符匹配多个分支或标签名称。
    branches:
      - ci/pipeline
    paths: # 通过路径触发工作流：这意味着当我在某些特定路径中的代码或文件进行某些更改时，希望触发此工作流。忽略路径和路径关键字支持使用通配符模式（* 和 **）匹配多个路径名称。
      - book-network-ui-vue/**
      - docker/frontend/**
      - docker-compose.yml
      - .github/workflows/*-frontend.yml

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code # 检查代码
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Extract project version # 提取项目版本号
        id: extract_version # 步骤的唯一标识符。可以在上下文中使用该ID来引用该步骤
        run: |
          cd book-network-ui-vue
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub # 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DH # 构建镜像并推送到DockerHub
        uses: docker/build-push-action@v5
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:${{ steps.extract_version.outputs.VERSION }}, ${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:latest # 为镜像指定名称和标签
          file: docker/frontend/Dockerfile # 指定 Dockerfile 的路径
          context: book-network-ui-vue # 若 Dockerfile 在前端项目根目录下，则无需提供后端项目文件名，为`.`即可
          push: 'true'
          platforms: linux/amd64

  deploy:
    name: Deploy frontend
    runs-on: ubuntu-22.04
    needs: [build-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create deployment folder
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{ secrets.ESC_HOST }}
          username: ${{ secrets.ESC_USERNAME }}
          key: ${{ secrets.ESC_SSH_KEY }}
          port: ${{ secrets.ESC_PORT }}
          script: |
            mkdir -p /ci-cd
      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ESC_HOST }}
          username: ${{ secrets.ESC_USERNAME }}
          key: ${{ secrets.ESC_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/ci-cd"  # 或你希望放置的目录
        
      - name: Deploy to ESC
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{ secrets.ESC_HOST }}
          username: ${{ secrets.ESC_USERNAME }}
          key: ${{ secrets.ESC_SSH_KEY }}
          port: ${{ secrets.ESC_PORT }}
          # passphrase: ${{ secrets.VPS_SSH_KEY_PASSPHRASE }} 有则添加
          script: |
            # Pull latest image
            docker compose -f docker-compose.yml pull
          
            # 停止并移除旧容器
            docker compose -f docker-compose.yml down
          
            # 启动新容器
            docker compose -f docker-compose.yml up -d
          
            # 清理旧镜像
            docker image prune -f
